### ISSUE TITLE
Crash when programmatically modifying object data

### ISSUE THREAD

**Issue by YakaryBovine** [Drake53/War3Api#21]
I'm experiencing a crash when starting the map in Warcraft III after modifying unit data programmatically. I think this was working before updating to the latest version.

This is the code causing an issue. If I remove it the crash goes away. (I normally modify a bunch of stuff; here I'm just demonstrating the issue).
```cs
    private static void ConfigureControlPointData(Map map)
    {
      var objectDatabase = map.GetObjectDatabaseFromMap();
      map.UnitObjectData = objectDatabase.GetAllData().UnitData;
    }
```

```cs
    public static ObjectDatabase GetObjectDatabaseFromMap(this Map map)
    {
      var objectDatabase = new ObjectDatabase();
      if (map.UnitObjectData != null) 
        objectDatabase.AddObjects(map.UnitObjectData);
      return objectDatabase;
    }
```

**Comment by Drake53** [comment]
Can't find `objectDatabase.AddObjects`, I'm guessing this is your own extension method? Can I see the implementation?

**Comment by YakaryBovine** [comment]
Hey Drake, apologies - I'm an idiot. `AddObjects` is part of the `War3Api.Object` namespace. However at some point I had compiled my own version of `War3Api.Object` to match my Warcraft 3 version. I forgot to update that when I updated `War3Net`, so I take it that must be the issue. 
I really thought at least one of the issues I was having today would be an actual issue with War3Net but I guess not!

**Comment by Drake53** [comment]
Good to hear you were able to figure out the issue.

**Comment by YakaryBovine** [comment]
Oops; I have now updated my `War3Api.Object` and the problem persists.

> Can't find `objectDatabase.AddObjects`, I'm guessing this is your own extension method? Can I see the implementation?

So to answer this question; `AddObjects` is from `War3Api.Object.ObjectDatabase`.

**Comment by Drake53** [comment]
Weird, when I use v1.31.1-rc.11 it only has Get/TryGet methods, while the GetObjects methods should already exist in this version when I check git history. Maybe I made some kind of mistake when publishing.

Can you check if the binary is the same after you run it through an ObjectDatabase without modifying it? If it's different you can also serialize to JSON to make it easier to spot the differences. I have a helper method in War3Net.TestTools.UnitTesting for checking if the binaries are equal:
```csharp
        public void Test()
        {
            var testMapPath = "";

            using var expectedStream = MpqFile.OpenRead(Path.Combine(testMapPath, UnitObjectData.MapFileName));
            using var reader = new BinaryReader(expectedStream);
            var expectedUnitObjectData = reader.ReadUnitObjectData();

            using var actualStream = new MemoryStream();
            using var writer = new BinaryWriter(actualStream);
            var actualUnitObjectData = GetUnitObjectData(testMapPath);
            writer.Write(actualUnitObjectData);
            writer.Flush();

            var options = GetJsonSerializerOptions();
            var expectedJson = JsonSerializer.Serialize(expectedUnitObjectData, options);
            var actualJson = JsonSerializer.Serialize(actualUnitObjectData, options);

            StreamAssert.AreEqual(expectedStream, actualStream, true);
        }

        private static UnitObjectData GetUnitObjectData(string mapPath)
        {
            var map = Map.Open(mapPath, MapFiles.UnitObjectData);
            var objectDatabase = GetObjectDatabaseFromMap(map);
            return objectDatabase.GetAllData().UnitData;
        }

        private static ObjectDatabase GetObjectDatabaseFromMap(Map map)
        {
            var objectDatabase = new ObjectDatabase();
            if (map.UnitObjectData != null)
            {
                objectDatabase.AddObjects(map.UnitObjectData);
            }

            return objectDatabase;
        }

        private static JsonSerializerOptions GetJsonSerializerOptions()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true,
            };

            options.Converters.Add(new JsonStringVersionConverter());

            return options;
        }
```

**Comment by YakaryBovine** [comment]
I executed the following code:
```cs
    private static void ConfigureControlPointData(Map map)
    {
      var objectDatabase = map.GetObjectDatabaseFromMap();
      var beforeProcessing = JsonSerializer.Serialize(map.UnitObjectData);
      var afterProcessing = JsonSerializer.Serialize(objectDatabase.GetAllData().UnitData);
      var beforeToken = JToken.Parse(beforeProcessing);
      var afterToken = JToken.Parse(afterProcessing);
      var jsonDiff = new JsonDiffPatch().Diff(beforeToken, afterToken);
      File.WriteAllText(@"C:\Users\zakar\RiderProjects\WarcraftLegacies-Fork\artifacts\jsonDiff.json", jsonDiff.ToString());
    }
```
```cs
    /// <summary>
    /// Creates an <see cref="ObjectDatabase"/> populated with data from the provided <see cref="Map"/>.
    /// </summary>
    public static ObjectDatabase GetObjectDatabaseFromMap(this Map map)
    {
      var objectDatabase = new ObjectDatabase();
      if (map.AbilityObjectData != null) objectDatabase.AddObjects(map.AbilityObjectData);
      if (map.BuffObjectData != null) objectDatabase.AddObjects(map.BuffObjectData);
      if (map.DestructableObjectData != null) objectDatabase.AddObjects(map.DestructableObjectData);
      if (map.DoodadObjectData != null) objectDatabase.AddObjects(map.DoodadObjectData);
      if (map.ItemObjectData != null) objectDatabase.AddObjects(map.ItemObjectData);
      if (map.UnitObjectData != null) objectDatabase.AddObjects(map.UnitObjectData);
      if (map.UpgradeObjectData != null) objectDatabase.AddObjects(map.UpgradeObjectData);
      return objectDatabase;
    }
```
Doing so produced the following diff: [jsonDiff.txt](https://github.com/Drake53/War3Api/files/12270955/jsonDiff.txt)
I can also confirm I have the latest version of `War3Net`, and my `War3Api.Object` is generated from the latest version of `War3Api.Object.Generator`.

**Comment by Drake53** [comment]
Never heard of JsonDiffPatch before, what's the best way to view this file?

**Comment by YakaryBovine** [comment]
> Never heard of JsonDiffPatch before, what's the best way to view this file?

Hey Drake, it's a tool that can indicate the differences between Json strings and output the values that are different. https://github.com/wbish/jsondiffpatch.net
I think the best way to view it would be to rename it to .json and open it in Notepad++ or some such. I did it this way so that you could see the actual differences in the file. So I think what this file is telling us is that, before processing, I have none of those `Unk` values, and that after, I have a whole heap of them.

**Comment by Drake53** [comment]
You sure it's not the other way around? The `ObjectDatabase.GetAllData()` method takes an optional formatversion parameter. Its default value is `Normal` (later renamed to `v2`). Patch 1.33 introduced `v3`, which is where all those `Unk`s come from.
Maybe the issue is that you save the files as v2, while your map still contains war3mapSkin object data files in v3 format.

**Comment by YakaryBovine** [comment]
Sorry yes I double-checked and you're correct. My `Map`'s `UnitObjectData` contains `Unk` values before I run `ConfigureControlPoints`, and doesn't contain any afterwards.
My `Map` is initialized using the `Map.Open` on a .w3x folder that was saved using the latest Warcraft 3 version, so it seems like all the formats should align just fine. I'll try investigate further.

**Comment by YakaryBovine** [comment]
Hi, I've been looking into this but I can't seem to get anywhere. It seems to me that the code I provided should be OK and that the `Unk` values should be retained. If I create and provide you a minimal example repo to test this with, would you be able to help me out?

**Comment by Drake53** [comment]
War3Api.Object models don't support the v3/unk values, so it's expected that these are lost when converting back and forth. The Unk values are currently represented as a list, so even if you supply v3 instead of the default v2 parameter to GetAllData, the result won't have any Unk values. I suspect that wc3 is unable to handle the object data files if they use different format versions, you can confirm this if you delete the war3mapSkin files from your map and only use v2 for the others. A workaround if you need to use v3 is to manually fill the Unk list. I still need to update this in War3Net anyways since apparently the documentation for these Unk values has been slightly updated.

**Comment by YakaryBovine** [comment]
Thankyou, I comprehend the problem now. Forcing the use of V2 has worked like a charm. Thankyou. Hopefully this helps someone else in the future!
