### ISSUE TITLE
War3Api.Object does not correctly set values for leveled ability fields

### ISSUE THREAD

**Issue by YakaryBovine** [Drake53/War3Api#8]
**Reproduction**
1. Download this source project: https://github.com/YakaryBovine/War3ApiBugDemonstration2
2. Run the Launcher project, then enter 2 into the console
3. Observe the hero "Big Uther" and his ability "Devotion Aura"

**Expected result**
The created hero is named Big Uther, his Devotion Aura ability has 4 levels, and his Devotion Aura ability grants 50 armor at every level.

**Actual result**
The created hero is named Big Uther, his Devotion Aura ability has 4 levels, and his Devotion Aura ability grants 1.5, 3, 4.5, or 4.5 armor depending on level. The latter is identical to unchanged vanilla behaviour.

**Note:** This was tested on Warcraft 3 version 1.32.

**Comment by Drake53** [comment]
Using the code you provided (and using 'binaryWriter.Write(objectDatabase.GetAllData());') I generated a .w3o file which works on 1.31.

Can you try generating a .w3o, import it in the world editor (object editor > file > import all object data), and check if the changes are properly imported (in the object editor itself and in-game)? If not, could you manually make the desired changes in the object editor and export it as .w3o so I can compare the files?

**Comment by YakaryBovine** [comment]
Yes, I'll do that as soon as I can!

**Comment by YakaryBovine** [comment]
Apologies; it looks like I was simply mistaken. The fix definitely works for me too.
