### ISSUE TITLE
Allow SimpleObjectModification to be cast to types derived from BaseObject

### ISSUE THREAD

**Issue by YakaryBovine** [Drake53/War3Api#9]
Doing so would allow War3Api.Object to be used to read **and** modify Warcraft 3 object data using its extraordinary API. Currently it is only efficient at writing data.

**Comment by Drake53** [comment]
I have added the method AddObjects(ObjectData objectData) to ObjectDatabase: https://github.com/Drake53/War3Api/commit/5eaf041e17248918a61ed09aecd0f1db94ba50c8

Also added AbilityFactory to easily create an Ability if you only have the type ID: https://github.com/Drake53/War3Api/commit/a481528c2c86a92a42797303eb6eeb241cc33c6f

Let me know if this solution works for you.

**Comment by YakaryBovine** [comment]
Incredible, thankyou. Your solution is much more user friendly. I'm unable to properly test it with my data due to #11 but I have high hopes.

**Comment by YakaryBovine** [comment]
Ok, I've been able to try it out. Everything works really well except for the fact that when I read my map data one of my destructibles gets added to the ObjectDatabase, but if I can figure out why that is I'll make another issue. For all I know my data is simply corrupt. Thanks again!

**Comment by YakaryBovine** [comment]
Ok, I've been able to try it out. Everything works really well except for the fact that when I read my map data one of my destructibles gets added to the ObjectDatabase, but if I can figure out why that is I'll make another issue. For all I know my data is simply corrupt. Thanks again!
